server.port=8083
spring.application.name=identity-service

eureka.client.service-url.defaultZone=http://localhost:8081/eureka/

spring.datasource.url=jdbc:postgresql://localhost:5433/identity_db
spring.datasource.username=harshit
spring.datasource.password=harshit1806
spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.security=DEBUG

jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437