server.port=8084
spring.application.name=destination-service

eureka.client.service-url.defaultZone=http://localhost:8081/eureka/

spring.datasource.url=jdbc:postgresql://localhost:5434/destination_db
spring.datasource.username=harshit
spring.datasource.password=harshit1806
spring.jpa.hibernate.ddl-auto=update

geodb.api.key=b4700d5a56mshc19b401188e9a7fp1537bbjsnc9360e785533
pexels.api.key=vzS9DNMz9IwuucXy7fKZC5qLXO1seEgTBup4dLPRKIKysbvx3uY8pns6
openweather.api.key=0c25c9ab9b746543b63ad9b60a12205b

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.ai.google.genai.api-key=AIzaSyDSOchXgIMlMlmFWfFC5q-H5Mphj5su1uo

spring.main.allow-bean-definition-overriding=true